name: My workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'luksuspanda.surge.sh'
          project: '.'
          login: 'leo.nielsen21@gmail.com'
          token: '1cf59040d88689ec37effeabfb8ef411'
